### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Sweet-l** [josephsdavid/semg_repro#1]
6353315
tcmalloc: large alloc 8455577600 bytes == 0x56112348a000
我报了这个错好像是内存的问题，该怎么解决？

**Comment by josephsdavid** [comment]
Hmm I have never seen that one before. It is probably an OOM error with the data loader, it takes a lot of memory to load the NinaPro dataset, and then there is a step which involves multiprocessing, which uses a LOT of memory. I can remove the multiprocessing and then it should resolve this if you like!

**Comment by josephsdavid** [comment]
Hey @Sweet-l, try using the branch in PR #4 and see if you still get this error! I probably won't fix on main, because the label generation process is painfully slow even with multiprocessing hogging all your memory
